### ISSUE TITLE
Use actual speed values for various materials

### ISSUE THREAD

**Issue by sdaitzman** [LaserQueue/DXFTimeEstimate#4]

**Comment by yrsegal** [comment]
more configs? more configs.

**Comment by sdaitzman** [comment]
more configs!

**Comment by yrsegal** [comment]
cooooooonfigs https://github.com/LaserQueue/DXFTimeEstimate/commit/81efadc55516374f0fc4caf4d29bacb161ef9c89

**Comment by sdaitzman** [comment]
closed by 34800a1
