### ISSUE TITLE
config.json needs a defaultconf.json

### ISSUE THREAD

**Issue by sdaitzman** [LaserQueue/DXFTimeEstimate#6]
Can be much simpler than in the main laserqueue - just take keys from `defaultconf.json` that don't exist in `config.json` and throw them into `config.json`.

Is this a standardized thing? If not, it should be. Plugins want configs.

**Comment by yrsegal** [comment]
mmk

I'll add a class to do this in util

**Comment by sdaitzman** [comment]
sweet :+1:
